repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: detect-aws-credentials
  - id: detect-private-key

- repo: https://github.com/tekwizely/pre-commit-golang
  rev: master
  hooks:
  - id: go-build-repo-mod
  - id: go-test-repo-mod
  - id: go-vet-repo-mod
  - id: go-fmt
  - id: go-lint
